### ISSUE TITLE
Method to destroy the animation?

### ISSUE THREAD

**Issue by thetrickster** [Auz/Bug#4]
Is there a method to destroy the bugs?  I've tried setting the controller class to a variable and tried setting it to null with no effect:

`var bugAnimate = new BugController();
...
...
bugAnimate = null;

Is there a way to destroy them once they've been instantiated?

**Comment by JimmyBoh** [comment]
That works on any bugs already created, but new ones continue to appear. Is there any way to stop everything? (I'd like to turn it completely off)

**Comment by Auz** [comment]
Ya, I think there is a bug with the timer, I'll take a look

**Comment by Auz** [comment]
Yep, found the bug

**Comment by Auz** [comment]
Thanks @JimmyBoh, should be fixed now.

**Comment by JimmyBoh** [comment]
Wow, nice hustle! FYI, I got this running in a [transparent electron window so it covers your desktop](https://github.com/jimmyboh/jk-overlay). I will be sure to have proper attribution for the first release.

**Comment by Auz** [comment]
Cool. Love to see it when you're done. I am pretty happy how the spiders turned out, considering I drew them by hand in photoshop. If someone throws their laptop across the room, are we liable? :)
-g 

    On Tuesday, June 28, 2016 8:45 AM, Jim Buck <notifications@github.com> wrote:
 

 Wow, nice hustle! FYI, I got this running in a transparent electron window so it covers your desktop. I will be sure to have proper attribution for the first release.—

**Comment by JimmyBoh** [comment]
_(Adding liability clause to top of todo list...)_

The spiders look great, even the dead ones. I would think making the legs look realistic despite all of the overlap would be tough. Great job!

As far as working builds, building from source works on Windows (clone, run `npm i`, then `npm start`). I will create a downloadable build soon, but unfortunately it will be an installer (portable app would make more sense from a prank use case). As for other platforms, I'll have to ask a buddy to build for macOS and Linux.
